2018-12-04T18:48:49.147: Classe do erro: excecao.InfraestruturaException   Metodo: inclui   Mensagem: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement <==> javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement <==> org.hibernate.exception.ConstraintViolationException: could not execute statement <==> could not execute statement <==> Column 'dataCriacao' cannot be null   Stack Trace: excecao.InfraestruturaException: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:62)
	at dao.impl.DocumentoDAOImpl$$EnhancerByCGLIB$$7cb18cb1.inclui(<generated>)
	at servico.impl.DocumentoAppServiceImpl.inclui(DocumentoAppServiceImpl.java:25)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34.CGLIB$inclui$5(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34$$FastClassByCGLIB$$d7ced366.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34.inclui(<generated>)
	at visao.DialogDocumento.inclui_aroundBody2(DialogDocumento.java:160)
	at visao.DialogDocumento$AjcClosure3.run(DialogDocumento.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at visao.DialogDocumento.actionPerformed(DialogDocumento.java:160)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at com.jtattoo.plaf.BaseButtonListener.mouseReleased(BaseButtonListener.java:60)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at dao.impl.JPADaoGenerico.inclui(JPADaoGenerico.java:36)
	at dao.impl.DocumentoDAOImpl$$EnhancerByCGLIB$$7cb18cb1.CGLIB$inclui$2(<generated>)
	at dao.impl.DocumentoDAOImpl$$EnhancerByCGLIB$$7cb18cb1$$FastClassByCGLIB$$11a7c68b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:59)
	... 49 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1316)
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:881)
	at dao.impl.JPADaoGenerico.inclui(JPADaoGenerico.java:34)
	... 53 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:74)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:136)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2975)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3487)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:377)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:214)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:194)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:178)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:321)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.ejb.event.EJB3PersistEventListener.saveWithGeneratedId(EJB3PersistEventListener.java:78)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:208)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:151)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:78)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:853)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:827)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:831)
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:875)
	... 54 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'dataCriacao' cannot be null
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:115)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1066)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1396)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1051)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:133)
	... 75 more
2018-12-04T19:05:05.508: Classe do erro: excecao.InfraestruturaException   Metodo: recuperaDocumento   Mensagem: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> could not extract ResultSet <==> Table 'trab.item' doesn't exist   Stack Trace: excecao.InfraestruturaException: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:62)
	at dao.impl.DocumentoDAOImpl$$EnhancerByCGLIB$$7cb18cb1.recuperaUmDocumentoEItens(<generated>)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumento(DocumentoAppServiceImpl.java:56)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34.CGLIB$recuperaDocumento$2(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34$$FastClassByCGLIB$$d7ced366.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$ca58c34.recuperaDocumento(<generated>)
	at visao.DialogDocumento.recuperaDocumento_aroundBody8(DialogDocumento.java:229)
	at visao.DialogDocumento$AjcClosure9.run(DialogDocumento.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at visao.DialogDocumento.actionPerformed(DialogDocumento.java:229)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at com.jtattoo.plaf.BaseButtonListener.mouseReleased(BaseButtonListener.java:60)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at dao.impl.JPADaoGenerico.busca(JPADaoGenerico.java:107)
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:57)
	... 49 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:316)
	at dao.impl.JPADaoGenerico.busca(JPADaoGenerico.java:101)
	... 50 more
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:61)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2040)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1837)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1816)
	at org.hibernate.loader.Loader.doQuery(Loader.java:900)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2526)
	at org.hibernate.loader.Loader.doList(Loader.java:2512)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2342)
	at org.hibernate.loader.Loader.list(Loader.java:2337)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:495)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:357)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1269)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:287)
	... 51 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'trab.item' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:56)
	... 66 more
2018-12-04T19:37:37.364: Classe do erro: excecao.InfraestruturaException   Metodo: recuperaDocumento   Mensagem: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> org.hibernate.exception.SQLGrammarException: could not extract ResultSet <==> could not extract ResultSet <==> Unknown column 'itens1_.DOCUMENTO_ID' in 'field list'   Stack Trace: excecao.InfraestruturaException: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:62)
	at dao.impl.DocumentoDAOImpl$$EnhancerByCGLIB$$50e60e21.recuperaUmDocumentoEItens(<generated>)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumento(DocumentoAppServiceImpl.java:56)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$e0da0da4.CGLIB$recuperaDocumento$0(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$e0da0da4$$FastClassByCGLIB$$241bb32c.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$e0da0da4.recuperaDocumento(<generated>)
	at visao.DialogDocumento.recuperaDocumento_aroundBody8(DialogDocumento.java:229)
	at visao.DialogDocumento$AjcClosure9.run(DialogDocumento.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at visao.DialogDocumento.actionPerformed(DialogDocumento.java:229)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at com.jtattoo.plaf.BaseButtonListener.mouseReleased(BaseButtonListener.java:60)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: excecao.InfraestruturaException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at dao.impl.JPADaoGenerico.busca(JPADaoGenerico.java:107)
	at dao.controle.InterceptadorDeDAO.intercept(InterceptadorDeDAO.java:57)
	... 49 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:316)
	at dao.impl.JPADaoGenerico.busca(JPADaoGenerico.java:101)
	... 50 more
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:61)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2040)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1837)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1816)
	at org.hibernate.loader.Loader.doQuery(Loader.java:900)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2526)
	at org.hibernate.loader.Loader.doList(Loader.java:2512)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2342)
	at org.hibernate.loader.Loader.list(Loader.java:2337)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:495)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:357)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1269)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:287)
	... 51 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'itens1_.DOCUMENTO_ID' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:56)
	... 66 more
2018-12-04T20:08:00.781: Classe do erro: java.lang.NullPointerException   Metodo: recuperaDocumentosPelaData   Mensagem:    Stack Trace: java.lang.NullPointerException
	at dao.impl.DocumentoDAOImpl.recuperaListaDeDocumentosPelaData(DocumentoDAOImpl.java:18)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumentosPelaData(DocumentoAppServiceImpl.java:81)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.CGLIB$recuperaDocumentosPelaData$3(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c$$FastClassByCGLIB$$dc258f0b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.recuperaDocumentosPelaData(<generated>)
	at Principal.recuperaDocumentosPelaData_aroundBody2(Principal.java:20)
	at Principal$AjcClosure3.run(Principal.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at Principal.main(Principal.java:20)
2018-12-04T20:10:25.050: Classe do erro: java.lang.NullPointerException   Metodo: recuperaDocumentosPelaData   Mensagem:    Stack Trace: java.lang.NullPointerException
	at dao.impl.DocumentoDAOImpl.recuperaListaDeDocumentosPelaData(DocumentoDAOImpl.java:18)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumentosPelaData(DocumentoAppServiceImpl.java:81)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.CGLIB$recuperaDocumentosPelaData$2(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c$$FastClassByCGLIB$$dc258f0b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.recuperaDocumentosPelaData(<generated>)
	at Principal.recuperaDocumentosPelaData_aroundBody2(Principal.java:20)
	at Principal$AjcClosure3.run(Principal.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at Principal.main(Principal.java:20)
2018-12-04T20:11:04.484: Classe do erro: java.lang.NullPointerException   Metodo: recuperaDocumentosPelaData   Mensagem:    Stack Trace: java.lang.NullPointerException
	at dao.impl.DocumentoDAOImpl.recuperaListaDeDocumentosPelaData(DocumentoDAOImpl.java:18)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumentosPelaData(DocumentoAppServiceImpl.java:81)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$21557e10.CGLIB$recuperaDocumentosPelaData$0(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$21557e10$$FastClassByCGLIB$$54895b29.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$21557e10.recuperaDocumentosPelaData(<generated>)
	at Principal.recuperaDocumentosPelaData_aroundBody2(Principal.java:20)
	at Principal$AjcClosure3.run(Principal.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at Principal.main(Principal.java:20)
2018-12-04T20:12:15.279: Classe do erro: java.lang.NullPointerException   Metodo: recuperaDocumentosPelaData   Mensagem:    Stack Trace: java.lang.NullPointerException
	at dao.impl.DocumentoDAOImpl.recuperaListaDeDocumentosPelaData(DocumentoDAOImpl.java:18)
	at servico.impl.DocumentoAppServiceImpl.recuperaDocumentosPelaData(DocumentoAppServiceImpl.java:81)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.CGLIB$recuperaDocumentosPelaData$5(<generated>)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c$$FastClassByCGLIB$$dc258f0b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at servico.controle.InterceptadorDeServico.intercept(InterceptadorDeServico.java:48)
	at servico.impl.DocumentoAppServiceImpl$$EnhancerByCGLIB$$51d11e2c.recuperaDocumentosPelaData(<generated>)
	at Principal.recuperaDocumentosPelaData_aroundBody2(Principal.java:20)
	at Principal$AjcClosure3.run(Principal.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at aspecto.AspectoAround.efetuaLog(AspectoAround.java:28)
	at Principal.main(Principal.java:20)
